version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7-jessie

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get install freetds-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint
          command: |
            . venv/bin/activate
            pylint --rcfile=pydistutils.cfg runcmd

      - run:
          name: Build
          command: |
            . venv/bin/activate
            python setup.py build
            python setup.py install sdist bdist_wheel

      - store_artifacts:
          path: dist
          destination: artifacts
