version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo deb http://deb.debian.org/debian stretch-backports main
            sudo apt-get -t stretch-backports install python-pymssql
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -q -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint
          command: |
            . venv/bin/activate
            pylint --rcfile=pydistutils.cfg runcmd

      - run:
          name: Build
          command: |
            . venv/bin/activate
            python3 setup.py build
            python3 setup.py install sdist bdist_wheel

      - store_artifacts:
          path: dist
          destination: artifacts
